In [19]:
import numpy as np


def task1() -> np.ndarray:
    array1 = np.arange(1, 11)
    return array1


def task2() -> np.ndarray:
    array2 = np.zeros((3, 3))
    return array2


def task3() -> np.ndarray:
    array3 = np.random.randint(1, 11, (5, 5))
    return array3


def task4() -> np.ndarray:
    array4 = np.random.rand(4, 4)
    return array4


def task5() -> None:
    array5 = np.random.randint(1, 11, 5)
    array6 = np.random.randint(1, 11, 5)
    addition_result = array5 + array6
    subtraction_result = array5 - array6
    multiplication_result = array5 * array6
    print("Завдання 5 (додавання):\n", addition_result)
    print("Завдання 5 (віднімання):\n", subtraction_result)
    print("Завдання 5 (множення):\n", multiplication_result)


def task6() -> float:
    vector1 = np.random.random(7)
    vector2 = np.random.random(7)
    scalar_product = np.dot(vector1, vector2)
    return scalar_product


# Додайте решту функцій для інших завдань аналогічно


def main() -> None:
    result1 = task1()
    print("Результат завдання 1:\n", result1)

    result2 = task2()
    print("Результат завдання 2:\n", result2)

    result3 = task3()
    print("Результат завдання 3:\n", result3)

    result4 = task4()
    print("Результат завдання 4:\n", result4)

    task5()

    result6 = task6()
    print("Результат завдання 6 (скалярний добуток):\n", result6)


if __name__ == "__main__":
    print("""
                        _        _  _  _  _     _  _  _  _     _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _     _
                _(_)_     (_)(_)(_)(_) _ (_)(_)(_)(_) _ (_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_) _       (_)
              _(_) (_)_   (_)         (_) (_)        (_)(_)               (_)         (_)      (_)            (_)(_)_     (_)
            _(_)     (_)_ (_) _  _  _ (_) (_) _  _  _(_)(_) _  _          (_)         (_)      (_) _  _       (_)  (_)_   (_)
          (_) _  _  _ (_)(_)(_)(_)(_)    (_)(_)(_)(_)_ (_)(_)(_)          (_)         (_)      (_)(_)(_)      (_)    (_)_ (_)
          (_)(_)(_)(_)(_)(_)   (_) _     (_)        (_)(_)                (_)         (_)      (_)            (_)      (_)(_)
          (_)         (_)(_)      (_) _  (_)_  _  _ (_)(_) _  _  _  _  _  (_) _       (_)      (_) _  _  _  _ (_)         (_)
          (_)         (_)(_)         (_)(_)(_)(_)(_)   (_)(_)(_)(_)(_) (_)(_)(_)      (_)      (_)(_)(_)(_)(_)(_)         (_)
    """)
    main()



                        _        _  _  _  _     _  _  _  _     _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _     _
                _(_)_     (_)(_)(_)(_) _ (_)(_)(_)(_) _ (_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_) _       (_)
              _(_) (_)_   (_)         (_) (_)        (_)(_)               (_)         (_)      (_)            (_)(_)_     (_)
            _(_)     (_)_ (_) _  _  _ (_) (_) _  _  _(_)(_) _  _          (_)         (_)      (_) _  _       (_)  (_)_   (_)
          (_) _  _  _ (_)(_)(_)(_)(_)    (_)(_)(_)(_)_ (_)(_)(_)          (_)         (_)      (_)(_)(_)      (_)    (_)_ (_)
          (_)(_)(_)(_)(_)(_)   (_) _     (_)        (_)(_)                (_)         (_)      (_)            (_)      (_)(_)
          (_)         (_)(_)      (_) _  (_)_  _  _ (_)(_) _  _  _  _  _  (_) _       (_)      (_) _  _  _  _ (_)         (_)
          (_)         (_)(_)         (_)(_)(_)(_)(_)   (_)(_)(_)(_)(_) (_)(_)(_)      (_)      (_)(_)(_)(_)(_)(_)     

In [18]:
import numpy as np
import logging

# Налаштування логів
logging.basicConfig(level=logging.INFO, format='%(message)s')


def task1() -> np.ndarray:
    array1 = np.arange(1, 11)
    logging.info("Виконано завдання 1")
    return array1


def task2() -> np.ndarray:
    array2 = np.zeros((3, 3))
    logging.info("Виконано завдання 2")
    return array2


def task3() -> np.ndarray:
    array3 = np.random.randint(1, 11, (5, 5))
    logging.info("Виконано завдання 3")
    return array3


def task4() -> np.ndarray:
    array4 = np.random.rand(4, 4)
    logging.info("Виконано завдання 4")
    return array4


def task5() -> None:
    array5 = np.random.randint(1, 11, 5)
    array6 = np.random.randint(1, 11, 5)
    addition_result = array5 + array6
    subtraction_result = array5 - array6
    multiplication_result = array5 * array6
    logging.info("Завдання 5 (додавання):\n%s", addition_result)
    logging.info("Завдання 5 (віднімання):\n%s", subtraction_result)
    logging.info("Завдання 5 (множення):\n%s", multiplication_result)
    logging.info("Виконано завдання 5")


def task6() -> float:
    vector1 = np.random.random(7)
    vector2 = np.random.random(7)
    scalar_product = np.dot(vector1, vector2)
    logging.info("Виконано завдання 6")
    return scalar_product


def main() -> None:
    result1 = task1()
    logging.info("Результат завдання 1:\n%s", result1)

    result2 = task2()
    logging.info("Результат завдання 2:\n%s", result2)

    result3 = task3()
    logging.info("Результат завдання 3:\n%s", result3)

    result4 = task4()
    logging.info("Результат завдання 4:\n%s", result4)

    task5()

    result6 = task6()
    logging.info("Результат завдання 6 (скалярний добуток):\n%s", result6)



if __name__ == "__main__":
    print("""
                        _        _  _  _  _     _  _  _  _     _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _     _
                _(_)_     (_)(_)(_)(_) _ (_)(_)(_)(_) _ (_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_) _       (_)
              _(_) (_)_   (_)         (_) (_)        (_)(_)               (_)         (_)      (_)            (_)(_)_     (_)
            _(_)     (_)_ (_) _  _  _ (_) (_) _  _  _(_)(_) _  _          (_)         (_)      (_) _  _       (_)  (_)_   (_)
          (_) _  _  _ (_)(_)(_)(_)(_)    (_)(_)(_)(_)_ (_)(_)(_)          (_)         (_)      (_)(_)(_)      (_)    (_)_ (_)
          (_)(_)(_)(_)(_)(_)   (_) _     (_)        (_)(_)                (_)         (_)      (_)            (_)      (_)(_)
          (_)         (_)(_)      (_) _  (_)_  _  _ (_)(_) _  _  _  _  _  (_) _       (_)      (_) _  _  _  _ (_)         (_)
          (_)         (_)(_)         (_)(_)(_)(_)(_)   (_)(_)(_)(_)(_) (_)(_)(_)      (_)      (_)(_)(_)(_)(_)(_)         (_)
    """)
    main()


Виконано завдання 1
Результат завдання 1:
[ 1  2  3  4  5  6  7  8  9 10]
Виконано завдання 2
Результат завдання 2:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Виконано завдання 3
Результат завдання 3:
[[ 2  4  4  4 10]
 [ 9  2 10  1  4]
 [ 2  8  6  2  6]
 [ 4  1  7  5  3]
 [ 7  5  3  5  9]]
Виконано завдання 4
Результат завдання 4:
[[0.96880416 0.89360393 0.76103167 0.07670096]
 [0.9325868  0.58393155 0.18962858 0.24789608]
 [0.68960484 0.79194489 0.69489062 0.33896148]
 [0.98053794 0.85456857 0.87817134 0.86344275]]
Завдання 5 (додавання):
[ 8 14  6 15 20]
Завдання 5 (віднімання):
[-2 -2  0  5  0]
Завдання 5 (множення):
[ 15  48   9  50 100]
Виконано завдання 5
Виконано завдання 6
Результат завдання 6 (скалярний добуток):
1.2033811117059876



                        _        _  _  _  _     _  _  _  _     _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _     _
                _(_)_     (_)(_)(_)(_) _ (_)(_)(_)(_) _ (_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_) _       (_)
              _(_) (_)_   (_)         (_) (_)        (_)(_)               (_)         (_)      (_)            (_)(_)_     (_)
            _(_)     (_)_ (_) _  _  _ (_) (_) _  _  _(_)(_) _  _          (_)         (_)      (_) _  _       (_)  (_)_   (_)
          (_) _  _  _ (_)(_)(_)(_)(_)    (_)(_)(_)(_)_ (_)(_)(_)          (_)         (_)      (_)(_)(_)      (_)    (_)_ (_)
          (_)(_)(_)(_)(_)(_)   (_) _     (_)        (_)(_)                (_)         (_)      (_)            (_)      (_)(_)
          (_)         (_)(_)      (_) _  (_)_  _  _ (_)(_) _  _  _  _  _  (_) _       (_)      (_) _  _  _  _ (_)         (_)
          (_)         (_)(_)         (_)(_)(_)(_)(_)   (_)(_)(_)(_)(_) (_)(_)(_)      (_)      (_)(_)(_)(_)(_)(_)     