In [1]:
import numpy as np


def task1() -> np.ndarray:
    array1 = np.arange(1, 11)
    return array1


def task2() -> np.ndarray:
    array2 = np.zeros((3, 3))
    return array2


def task3() -> np.ndarray:
    array3 = np.random.randint(1, 11, (5, 5))
    return array3


def task4() -> np.ndarray:
    array4 = np.random.rand(4, 4)
    return array4


def task5() -> np.ndarray:
    array5 = np.random.randint(1, 11, 5)
    array6 = np.random.randint(1, 11, 5)
    addition_result = array5 + array6
    subtraction_result = array5 - array6
    multiplication_result = array5 * array6
    return addition_result, subtraction_result, multiplication_result


def task6() -> float:
    vector1 = np.random.random(7)
    vector2 = np.random.random(7)
    scalar_product = np.dot(vector1, vector2)
    return scalar_product


def task7() -> np.ndarray:
    matrix1 = np.random.randint(1, 11, (2, 2))
    matrix2 = np.random.randint(1, 11, (2, 3))
    result = np.dot(matrix1, matrix2)
    return result


def task8() -> np.ndarray:
    matrix = np.random.randint(1, 11, (3, 3))
    inverted_matrix = np.linalg.inv(matrix)
    return inverted_matrix


def task9() -> np.ndarray:
    matrix = np.random.rand(4, 4)
    transposed_matrix = np.transpose(matrix)
    return transposed_matrix


def task10() -> np.ndarray:
    matrix = np.random.randint(1, 11, (3, 4))
    vector = np.random.randint(1, 11, 4)
    result = np.dot(matrix, vector)
    return result


def task11() -> np.ndarray:
    matrix = np.random.random((2, 3))
    vector = np.random.random(3)
    result = np.dot(matrix, vector)
    return result


def task12() -> np.ndarray:
    matrix1 = np.random.randint(1, 11, (2, 2))
    matrix2 = np.random.randint(1, 11, (2, 2))
    result = np.multiply(matrix1, matrix2)
    return result


def task13() -> np.ndarray:
    matrix1 = np.random.randint(1, 11, (2, 2))
    matrix2 = np.random.randint(1, 11, (2, 2))
    result = np.dot(matrix1, matrix2)
    return result


def task14() -> int:
    matrix = np.random.randint(1, 101, (5, 5))
    total_sum = np.sum(matrix)
    return total_sum


def task15() -> np.ndarray:
    matrix1 = np.random.randint(1, 11, (4, 4))
    matrix2 = np.random.randint(1, 11, (4, 4))
    result = matrix1 - matrix2
    return result


def task16() -> np.ndarray:
    matrix = np.random.random((3, 3))
    row_sums = np.sum(matrix, axis=1)
    return row_sums


def task17() -> np.ndarray:
    matrix = np.random.randint(1, 11, (3, 4))
    squared_matrix = np.square(matrix)
    return squared_matrix


def task18() -> np.ndarray:
    vector = np.random.randint(1, 51, 4)
    square_root_vector = np.sqrt(vector)
    return square_root_vector


def main() -> None:
    result1 = task1()
    print("Результат завдання 1:\n", result1)

    result2 = task2()
    print("Результат завдання 2:\n", result2)

    result3 = task3()
    print("Результат завдання 3:\n", result3)

    result4 = task4()
    print("Результат завдання 4:\n", result4)

    result5_add, result5_sub, result5_mult = task5()
    print("Результат завдання 5 (додавання):\n", result5_add)
    print("Результат завдання 5 (віднімання):\n", result5_sub)
    print("Результат завдання 5 (множення):\n", result5_mult)

    result6 = task6()
    print("Результат завдання 6 (скалярний добуток):\n", result6)

    result7 = task7()
    print("Результат завдання 7:\n", result7)

    result8 = task8()
    print("Результат завдання 8:\n", result8)

    result9 = task9()
    print("Результат завдання 9:\n", result9)

    result10 = task10()
    print("Результат завдання 10:\n", result10)

    result11 = task11()
    print("Результат завдання 11:\n", result11)

    result12 = task12()
    print("Результат завдання 12:\n", result12)

    result13 = task13()
    print("Результат завдання 13:\n", result13)

    result14 = task14()
    print("Результат завдання 14:\n", result14)

    result15 = task15()
    print("Результат завдання 15:\n", result15)

    result16 = task16()
    print("Результат завдання 16:\n", result16)

    result17 = task17()
    print("Результат завдання 17:\n", result17)

    result18 = task18()
    print("Результат завдання 18:\n", result18)


if __name__ == "__main__":
    print("""
                        _        _  _  _  _     _  _  _  _     _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _     _
                _(_)_     (_)(_)(_)(_) _ (_)(_)(_)(_) _ (_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_) _       (_)
              _(_) (_)_   (_)         (_) (_)        (_)(_)               (_)         (_)      (_)            (_)(_)_     (_)
            _(_)     (_)_ (_) _  _  _ (_) (_) _  _  _(_)(_) _  _          (_)         (_)      (_) _  _       (_)  (_)_   (_)
          (_) _  _  _ (_)(_)(_)(_)(_)    (_)(_)(_)(_)_ (_)(_)(_)          (_)         (_)      (_)(_)(_)      (_)    (_)_ (_)
          (_)(_)(_)(_)(_)(_)   (_) _     (_)        (_)(_)                (_)         (_)      (_)            (_)      (_)(_)
          (_)         (_)(_)      (_) _  (_)_  _  _ (_)(_) _  _  _  _  _  (_) _       (_)      (_) _  _  _  _ (_)         (_)
          (_)         (_)(_)         (_)(_)(_)(_)(_)   (_)(_)(_)(_)(_) (_)(_)(_)      (_)      (_)(_)(_)(_)(_)(_)         (_)
    """)
    main()



                        _        _  _  _  _     _  _  _  _     _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _     _
                _(_)_     (_)(_)(_)(_) _ (_)(_)(_)(_) _ (_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_) _       (_)
              _(_) (_)_   (_)         (_) (_)        (_)(_)               (_)         (_)      (_)            (_)(_)_     (_)
            _(_)     (_)_ (_) _  _  _ (_) (_) _  _  _(_)(_) _  _          (_)         (_)      (_) _  _       (_)  (_)_   (_)
          (_) _  _  _ (_)(_)(_)(_)(_)    (_)(_)(_)(_)_ (_)(_)(_)          (_)         (_)      (_)(_)(_)      (_)    (_)_ (_)
          (_)(_)(_)(_)(_)(_)   (_) _     (_)        (_)(_)                (_)         (_)      (_)            (_)      (_)(_)
          (_)         (_)(_)      (_) _  (_)_  _  _ (_)(_) _  _  _  _  _  (_) _       (_)      (_) _  _  _  _ (_)         (_)
          (_)         (_)(_)         (_)(_)(_)(_)(_)   (_)(_)(_)(_)(_) (_)(_)(_)      (_)      (_)(_)(_)(_)(_)(_)     

In [2]:
import numpy as np
import logging

# Налаштування логування
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')


def task1() -> np.ndarray:
    array1 = np.arange(1, 11)
    logging.info(f"task1 output: \n{array1}")
    return array1


def task2() -> np.ndarray:
    array2 = np.zeros((3, 3))
    logging.info(f"task2 output: \n{array2}")
    return array2


def task3() -> np.ndarray:
    array3 = np.random.randint(1, 11, (5, 5))
    logging.info(f"task3 output: \n{array3}")
    return array3


def task4() -> np.ndarray:
    array4 = np.random.rand(4, 4)
    logging.info(f"task4 output: \n{array4}")
    return array4


def task5() -> np.ndarray:
    array5 = np.random.randint(1, 11, 5)
    array6 = np.random.randint(1, 11, 5)

    logging.info(f"task5: array5 values: \n{array5}")
    logging.info(f"task5: array6 values: \n{array6}")

    addition_result = array5 + array6
    subtraction_result = array5 - array6
    multiplication_result = array5 * array6

    logging.info(f"task5: addition_result: \n{addition_result}")
    logging.info(f"task5: subtraction_result: \n{subtraction_result}")
    logging.info(f"task5: multiplication_result: \n{multiplication_result}")

    return addition_result, subtraction_result, multiplication_result


def task6() -> float:
    vector1 = np.random.random(7)
    vector2 = np.random.random(7)
    scalar_product = np.dot(vector1, vector2)
    logging.info(f"task6: scalar_product: \n{scalar_product}")
    return scalar_product


def task7() -> np.ndarray:
    matrix1 = np.random.randint(1, 11, (2, 2))
    matrix2 = np.random.randint(1, 11, (2, 3))
    result = np.dot(matrix1, matrix2)
    logging.info(f"task7: result: \n{result}")
    return result


def task8() -> np.ndarray:
    matrix = np.random.randint(1, 11, (3, 3))
    logging.info(f"task8: matrix : \n{matrix }")
    inverted_matrix = np.linalg.inv(matrix)
    logging.info(f"task8: inverted_matrix: \n{inverted_matrix}")
    return inverted_matrix


def task9() -> np.ndarray:
    matrix = np.random.rand(4, 4)
    logging.info(f"task9: matrix: \n{matrix}")
    transposed_matrix = np.transpose(matrix)
    logging.info(f"task9: transposed_matrix: \n{transposed_matrix}")
    return transposed_matrix


def task10() -> np.ndarray:
    matrix = np.random.randint(1, 11, (3, 4))
    logging.info(f"task10: matrix: \n{matrix}")
    vector = np.random.randint(1, 11, 4)
    logging.info(f"task10: vector: \n{vector}")
    result = np.dot(matrix, vector)
    logging.info(f"task10: result: \n{result}")
    return result


def task11() -> np.ndarray:
    matrix = np.random.random((2, 3))
    logging.info(f"task11: result: \n{matrix}")
    vector = np.random.random(3)
    logging.info(f"task11: result: \n{vector}")
    result = np.dot(matrix, vector)
    logging.info(f"task11: result: \n{result}")
    return result


def task12() -> np.ndarray:
    matrix1 = np.random.randint(1, 11, (2, 2))
    matrix2 = np.random.randint(1, 11, (2, 2))
    logging.info(f"task12: matrix1: \n{matrix1}")
    logging.info(f"task12: matrix2: \n{matrix2}")
    result = np.multiply(matrix1, matrix2)
    logging.info(f"task12: result: \n{result}")
    return result


def task13() -> np.ndarray:
    matrix1 = np.random.randint(1, 11, (2, 2))
    matrix2 = np.random.randint(1, 11, (2, 2))
    logging.info(f"task13: matrix1: \n{matrix1}")
    logging.info(f"task13: matrix2: \n{matrix2}")
    result = np.dot(matrix1, matrix2)
    logging.info(f"task13: result: \n{result}")
    return result


def task14() -> int:
    matrix = np.random.randint(1, 101, (5, 5))
    logging.info(f"task14: matrix: \n{matrix}")
    total_sum = np.sum(matrix)
    logging.info(f"task14: total_sum: {total_sum}")
    return total_sum


def task15() -> np.ndarray:
    matrix1 = np.random.randint(1, 11, (4, 4))
    matrix2 = np.random.randint(1, 11, (4, 4))
    logging.info(f"task15: matrix1: \n{matrix1}")
    logging.info(f"task15: matrix2: \n{matrix2}")
    result = matrix1 - matrix2
    logging.info(f"task15: result: \n{result}")
    return result


def task16() -> np.ndarray:
    matrix = np.random.random((3, 3))
    logging.info(f"task16: matrix: \n{matrix}")
    row_sums = np.sum(matrix, axis=1)
    logging.info(f"task16: row_sums: {row_sums}")
    return row_sums


def task17() -> np.ndarray:
    matrix = np.random.randint(1, 11, (3, 4))
    logging.info(f"task17: matrix: \n{matrix}")
    squared_matrix = np.square(matrix)
    logging.info(f"task17: squared_matrix: \n{squared_matrix}")
    return squared_matrix


def task18() -> np.ndarray:
    vector = np.random.randint(1, 51, 4)
    logging.info(f"task18: vector: {vector}")
    square_root_vector = np.sqrt(vector)
    logging.info(f"task18: square_root_vector: {square_root_vector}")
    return square_root_vector


def main():
    logging.info("Starting the main function...")

    task1()
    task2()
    task3()
    task4()
    task5()
    task6()
    task7()
    task8()
    task9()
    task10()
    task11()
    task12()
    task13()
    task14()
    task15()
    task16()
    task17()
    task18()

    logging.info("Finished executing all tasks in the main function.")

if __name__ == "__main__":
    print("""
                        _        _  _  _  _     _  _  _  _     _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _     _
                _(_)_     (_)(_)(_)(_) _ (_)(_)(_)(_) _ (_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_) _       (_)
              _(_) (_)_   (_)         (_) (_)        (_)(_)               (_)         (_)      (_)            (_)(_)_     (_)
            _(_)     (_)_ (_) _  _  _ (_) (_) _  _  _(_)(_) _  _          (_)         (_)      (_) _  _       (_)  (_)_   (_)
          (_) _  _  _ (_)(_)(_)(_)(_)    (_)(_)(_)(_)_ (_)(_)(_)          (_)         (_)      (_)(_)(_)      (_)    (_)_ (_)
          (_)(_)(_)(_)(_)(_)   (_) _     (_)        (_)(_)                (_)         (_)      (_)            (_)      (_)(_)
          (_)         (_)(_)      (_) _  (_)_  _  _ (_)(_) _  _  _  _  _  (_) _       (_)      (_) _  _  _  _ (_)         (_)
          (_)         (_)(_)         (_)(_)(_)(_)(_)   (_)(_)(_)(_)(_) (_)(_)(_)      (_)      (_)(_)(_)(_)(_)(_)         (_)
    """)
    main()

2023-08-10 01:20:02,988 - INFO - Starting the main function...
2023-08-10 01:20:02,990 - INFO - task1 output: 
[ 1  2  3  4  5  6  7  8  9 10]
2023-08-10 01:20:02,991 - INFO - task2 output: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2023-08-10 01:20:02,992 - INFO - task3 output: 
[[4 8 7 4 5]
 [8 1 1 3 7]
 [2 5 4 2 1]
 [3 8 5 1 8]
 [1 4 8 7 8]]
2023-08-10 01:20:02,993 - INFO - task4 output: 
[[0.82412387 0.95301381 0.75799089 0.39919259]
 [0.41478573 0.6815234  0.29075046 0.36757464]
 [0.08663572 0.77698009 0.40188106 0.82703735]
 [0.45086961 0.5491659  0.31947233 0.10125771]]
2023-08-10 01:20:02,994 - INFO - task5: array5 values: 
[10  9  9  6  2]
2023-08-10 01:20:02,994 - INFO - task5: array6 values: 
[ 2  5  3 10  2]
2023-08-10 01:20:02,995 - INFO - task5: addition_result: 
[12 14 12 16  4]
2023-08-10 01:20:02,996 - INFO - task5: subtraction_result: 
[ 8  4  6 -4  0]
2023-08-10 01:20:02,996 - INFO - task5: multiplication_result: 
[20 45 27 60  4]
2023-08-10 01:20:02,997 - INFO - task6: s


                        _        _  _  _  _     _  _  _  _     _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _     _
                _(_)_     (_)(_)(_)(_) _ (_)(_)(_)(_) _ (_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_) _       (_)
              _(_) (_)_   (_)         (_) (_)        (_)(_)               (_)         (_)      (_)            (_)(_)_     (_)
            _(_)     (_)_ (_) _  _  _ (_) (_) _  _  _(_)(_) _  _          (_)         (_)      (_) _  _       (_)  (_)_   (_)
          (_) _  _  _ (_)(_)(_)(_)(_)    (_)(_)(_)(_)_ (_)(_)(_)          (_)         (_)      (_)(_)(_)      (_)    (_)_ (_)
          (_)(_)(_)(_)(_)(_)   (_) _     (_)        (_)(_)                (_)         (_)      (_)            (_)      (_)(_)
          (_)         (_)(_)      (_) _  (_)_  _  _ (_)(_) _  _  _  _  _  (_) _       (_)      (_) _  _  _  _ (_)         (_)
          (_)         (_)(_)         (_)(_)(_)(_)(_)   (_)(_)(_)(_)(_) (_)(_)(_)      (_)      (_)(_)(_)(_)(_)(_)     