In [1]:
import numpy as np


def task1() -> np.ndarray:
    array1 = np.arange(1, 11)
    return array1


def task2() -> np.ndarray:
    array2 = np.zeros((3, 3))
    return array2


def task3() -> np.ndarray:
    array3 = np.random.randint(1, 11, (5, 5))
    return array3


def task4() -> np.ndarray:
    array4 = np.random.rand(4, 4)
    return array4


def task5() -> np.ndarray:
    array5 = np.random.randint(1, 11, 5)
    array6 = np.random.randint(1, 11, 5)
    addition_result = array5 + array6
    subtraction_result = array5 - array6
    multiplication_result = array5 * array6
    return addition_result, subtraction_result, multiplication_result


def task6() -> float:
    vector1 = np.random.random(7)
    vector2 = np.random.random(7)
    scalar_product = np.dot(vector1, vector2)
    return scalar_product


def task7() -> np.ndarray:
    matrix1 = np.random.randint(1, 11, (2, 2))
    matrix2 = np.random.randint(1, 11, (2, 3))
    result = np.dot(matrix1, matrix2)
    return result


def task8() -> np.ndarray:
    matrix = np.random.randint(1, 11, (3, 3))
    inverted_matrix = np.linalg.inv(matrix)
    return inverted_matrix


def task9() -> np.ndarray:
    matrix = np.random.rand(4, 4)
    transposed_matrix = np.transpose(matrix)
    return transposed_matrix


def task10() -> np.ndarray:
    matrix = np.random.randint(1, 11, (3, 4))
    vector = np.random.randint(1, 11, 4)
    result = np.dot(matrix, vector)
    return result


def task11() -> np.ndarray:
    matrix = np.random.random((2, 3))
    vector = np.random.random(3)
    result = np.dot(matrix, vector)
    return result


def task12() -> np.ndarray:
    matrix1 = np.random.randint(1, 11, (2, 2))
    matrix2 = np.random.randint(1, 11, (2, 2))
    result = np.multiply(matrix1, matrix2)
    return result


def task13() -> np.ndarray:
    matrix1 = np.random.randint(1, 11, (2, 2))
    matrix2 = np.random.randint(1, 11, (2, 2))
    result = np.dot(matrix1, matrix2)
    return result


def task14() -> int:
    matrix = np.random.randint(1, 101, (5, 5))
    total_sum = np.sum(matrix)
    return total_sum


def task15() -> np.ndarray:
    matrix1 = np.random.randint(1, 11, (4, 4))
    matrix2 = np.random.randint(1, 11, (4, 4))
    result = matrix1 - matrix2
    return result


def task16() -> np.ndarray:
    matrix = np.random.random((3, 3))
    row_sums = np.sum(matrix, axis=1)
    return row_sums


def task17() -> np.ndarray:
    matrix = np.random.randint(1, 11, (3, 4))
    squared_matrix = np.square(matrix)
    return squared_matrix


def task18() -> np.ndarray:
    vector = np.random.randint(1, 51, 4)
    square_root_vector = np.sqrt(vector)
    return square_root_vector


def main() -> None:
    result1 = task1()
    print("Результат завдання 1:\n", result1)

    result2 = task2()
    print("Результат завдання 2:\n", result2)

    result3 = task3()
    print("Результат завдання 3:\n", result3)

    result4 = task4()
    print("Результат завдання 4:\n", result4)

    result5_add, result5_sub, result5_mult = task5()
    print("Результат завдання 5 (додавання):\n", result5_add)
    print("Результат завдання 5 (віднімання):\n", result5_sub)
    print("Результат завдання 5 (множення):\n", result5_mult)

    result6 = task6()
    print("Результат завдання 6 (скалярний добуток):\n", result6)

    result7 = task7()
    print("Результат завдання 7:\n", result7)

    result8 = task8()
    print("Результат завдання 8:\n", result8)

    result9 = task9()
    print("Результат завдання 9:\n", result9)

    result10 = task10()
    print("Результат завдання 10:\n", result10)

    result11 = task11()
    print("Результат завдання 11:\n", result11)

    result12 = task12()
    print("Результат завдання 12:\n", result12)

    result13 = task13()
    print("Результат завдання 13:\n", result13)

    result14 = task14()
    print("Результат завдання 14:\n", result14)

    result15 = task15()
    print("Результат завдання 15:\n", result15)

    result16 = task16()
    print("Результат завдання 16:\n", result16)

    result17 = task17()
    print("Результат завдання 17:\n", result17)

    result18 = task18()
    print("Результат завдання 18:\n", result18)


if __name__ == "__main__":
    print("""
                        _        _  _  _  _     _  _  _  _     _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _     _
                _(_)_     (_)(_)(_)(_) _ (_)(_)(_)(_) _ (_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_) _       (_)
              _(_) (_)_   (_)         (_) (_)        (_)(_)               (_)         (_)      (_)            (_)(_)_     (_)
            _(_)     (_)_ (_) _  _  _ (_) (_) _  _  _(_)(_) _  _          (_)         (_)      (_) _  _       (_)  (_)_   (_)
          (_) _  _  _ (_)(_)(_)(_)(_)    (_)(_)(_)(_)_ (_)(_)(_)          (_)         (_)      (_)(_)(_)      (_)    (_)_ (_)
          (_)(_)(_)(_)(_)(_)   (_) _     (_)        (_)(_)                (_)         (_)      (_)            (_)      (_)(_)
          (_)         (_)(_)      (_) _  (_)_  _  _ (_)(_) _  _  _  _  _  (_) _       (_)      (_) _  _  _  _ (_)         (_)
          (_)         (_)(_)         (_)(_)(_)(_)(_)   (_)(_)(_)(_)(_) (_)(_)(_)      (_)      (_)(_)(_)(_)(_)(_)         (_)
    """)
    main()



                        _        _  _  _  _     _  _  _  _     _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _     _
                _(_)_     (_)(_)(_)(_) _ (_)(_)(_)(_) _ (_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_) _       (_)
              _(_) (_)_   (_)         (_) (_)        (_)(_)               (_)         (_)      (_)            (_)(_)_     (_)
            _(_)     (_)_ (_) _  _  _ (_) (_) _  _  _(_)(_) _  _          (_)         (_)      (_) _  _       (_)  (_)_   (_)
          (_) _  _  _ (_)(_)(_)(_)(_)    (_)(_)(_)(_)_ (_)(_)(_)          (_)         (_)      (_)(_)(_)      (_)    (_)_ (_)
          (_)(_)(_)(_)(_)(_)   (_) _     (_)        (_)(_)                (_)         (_)      (_)            (_)      (_)(_)
          (_)         (_)(_)      (_) _  (_)_  _  _ (_)(_) _  _  _  _  _  (_) _       (_)      (_) _  _  _  _ (_)         (_)
          (_)         (_)(_)         (_)(_)(_)(_)(_)   (_)(_)(_)(_)(_) (_)(_)(_)      (_)      (_)(_)(_)(_)(_)(_)     

In [2]:
import numpy as np
import logging

# Налаштування логів
logging.basicConfig(level=logging.INFO, format='%(message)s')


def task1() -> np.ndarray:
    array1 = np.arange(1, 11)
    logging.info("Виконано завдання 1")
    return array1


def task2() -> np.ndarray:
    array2 = np.zeros((3, 3))
    logging.info("Виконано завдання 2")
    return array2


def task3() -> np.ndarray:
    array3 = np.random.randint(1, 11, (5, 5))
    logging.info("Виконано завдання 3")
    return array3


def task4() -> np.ndarray:
    array4 = np.random.rand(4, 4)
    logging.info("Виконано завдання 4")
    return array4


def task5() -> None:
    array5 = np.random.randint(1, 11, 5)
    array6 = np.random.randint(1, 11, 5)
    addition_result = array5 + array6
    subtraction_result = array5 - array6
    multiplication_result = array5 * array6
    logging.info("Завдання 5 (додавання):\n%s", addition_result)
    logging.info("Завдання 5 (віднімання):\n%s", subtraction_result)
    logging.info("Завдання 5 (множення):\n%s", multiplication_result)
    logging.info("Виконано завдання 5")


def task6() -> float:
    vector1 = np.random.random(7)
    vector2 = np.random.random(7)
    scalar_product = np.dot(vector1, vector2)
    logging.info("Виконано завдання 6")
    return scalar_product


def main() -> None:
    result1 = task1()
    logging.info("Результат завдання 1:\n%s", result1)

    result2 = task2()
    logging.info("Результат завдання 2:\n%s", result2)

    result3 = task3()
    logging.info("Результат завдання 3:\n%s", result3)

    result4 = task4()
    logging.info("Результат завдання 4:\n%s", result4)

    task5()

    result6 = task6()
    logging.info("Результат завдання 6 (скалярний добуток):\n%s", result6)



if __name__ == "__main__":
    print("""
                        _        _  _  _  _     _  _  _  _     _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _     _
                _(_)_     (_)(_)(_)(_) _ (_)(_)(_)(_) _ (_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_) _       (_)
              _(_) (_)_   (_)         (_) (_)        (_)(_)               (_)         (_)      (_)            (_)(_)_     (_)
            _(_)     (_)_ (_) _  _  _ (_) (_) _  _  _(_)(_) _  _          (_)         (_)      (_) _  _       (_)  (_)_   (_)
          (_) _  _  _ (_)(_)(_)(_)(_)    (_)(_)(_)(_)_ (_)(_)(_)          (_)         (_)      (_)(_)(_)      (_)    (_)_ (_)
          (_)(_)(_)(_)(_)(_)   (_) _     (_)        (_)(_)                (_)         (_)      (_)            (_)      (_)(_)
          (_)         (_)(_)      (_) _  (_)_  _  _ (_)(_) _  _  _  _  _  (_) _       (_)      (_) _  _  _  _ (_)         (_)
          (_)         (_)(_)         (_)(_)(_)(_)(_)   (_)(_)(_)(_)(_) (_)(_)(_)      (_)      (_)(_)(_)(_)(_)(_)         (_)
    """)
    main()


Виконано завдання 1
Результат завдання 1:
[ 1  2  3  4  5  6  7  8  9 10]
Виконано завдання 2
Результат завдання 2:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Виконано завдання 3
Результат завдання 3:
[[ 9  6  4  7  5]
 [10  1  8  2  9]
 [ 5 10  2  1  9]
 [10  2  4  4  4]
 [ 6  4  4  7 10]]
Виконано завдання 4
Результат завдання 4:
[[0.00991532 0.48065526 0.11578197 0.98333581]
 [0.33058197 0.34558836 0.50858168 0.16106523]
 [0.54694975 0.8241944  0.45666203 0.07618344]
 [0.01961984 0.05071502 0.41579305 0.8739937 ]]
Завдання 5 (додавання):
[11  8  7 15  9]
Завдання 5 (віднімання):
[-7  0 -5  3  5]
Завдання 5 (множення):
[18 16  6 54 14]
Виконано завдання 5
Виконано завдання 6
Результат завдання 6 (скалярний добуток):
1.3292798764587976



                        _        _  _  _  _     _  _  _  _     _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _     _
                _(_)_     (_)(_)(_)(_) _ (_)(_)(_)(_) _ (_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_)(_) _       (_)
              _(_) (_)_   (_)         (_) (_)        (_)(_)               (_)         (_)      (_)            (_)(_)_     (_)
            _(_)     (_)_ (_) _  _  _ (_) (_) _  _  _(_)(_) _  _          (_)         (_)      (_) _  _       (_)  (_)_   (_)
          (_) _  _  _ (_)(_)(_)(_)(_)    (_)(_)(_)(_)_ (_)(_)(_)          (_)         (_)      (_)(_)(_)      (_)    (_)_ (_)
          (_)(_)(_)(_)(_)(_)   (_) _     (_)        (_)(_)                (_)         (_)      (_)            (_)      (_)(_)
          (_)         (_)(_)      (_) _  (_)_  _  _ (_)(_) _  _  _  _  _  (_) _       (_)      (_) _  _  _  _ (_)         (_)
          (_)         (_)(_)         (_)(_)(_)(_)(_)   (_)(_)(_)(_)(_) (_)(_)(_)      (_)      (_)(_)(_)(_)(_)(_)     